add mfg dialog changes
Parspec/parspec-pixel pull request #154
Opened 2023-06-05 15:03 UTC by sunnyparspec21

2023-07-05 09:54 UTC, Charul-Parspec requested changes

2023-07-05 09:54 UTC, Charul-Parspec commented on src/components/AutoComplete/Autocomplete.tsx
> +    filterOptionsCallBack?: (options: OptionType[], params: any) => OptionType[];
@komalkiri define specific type for params(tip. hover over filterOptions prop in MuiAutocomplete, you will get the typ)

2023-07-05 12:18 UTC, komalkiri commented on src/components/AutoComplete/Autocomplete.tsx
> +    filterOptionsCallBack?: (options: OptionType[], params: any) => OptionType[];
Done

2023-07-06 11:20 UTC, Charul-Parspec approved these changes

2023-07-20 05:17 UTC, sunnyparspec21 reviewed
looks good to me

2023-07-26 06:28 UTC, abhijit-parspec commented on src/components/Table/Table.tsx
> +    selectedItemsBelowSearch: false
```suggestion
    showSelectedItemsCountBelowSearch: false
```

2023-07-26 06:30 UTC, abhijit-parspec commented on src/components/Table/Table.tsx
> +                <Box p={1} pl={3} pr={2} mb={2} bgcolor={'primary.main'} color={'secondary.contrastText'} display="flex" alignItems="center" gap={2} width={'max-content'}>
```suggestion
                SelectedItemsCount
```

2023-07-26 06:45 UTC, abhijit-parspec approved these changes

2023-07-26 06:45 UTC, merged