Md 6802 - Table component update
Parspec/parspec-pixel pull request #168
Opened 2023-06-15 06:49 UTC by Charul-Parspec

2023-09-15 11:34 UTC, atul2103 approved these changes

2023-10-13 06:42 UTC, sunnyparspec21 requested changes

2023-10-13 06:42 UTC, sunnyparspec21 commented on src/components/Table/Table.tsx
>          // tableRef.current.grid.notify('freezerender', { case: 'refreshHeight' });
is this commented code required? if not ew can remove this.

2023-10-13 07:15 UTC, atul2103 commented on src/components/Table/Table.tsx
> +                    setTableHeight(currentNode.clientHeight - toolbarHeight - 8);
we were subtraction tableHeader in previous calculation, is that not needed here ?

2023-10-13 07:37 UTC, Charul-Parspec commented on src/components/Table/Table.tsx
> +                    setTableHeight(currentNode.clientHeight - toolbarHeight - 8);
@atul2103 no we don't need it now since height value is assigned to container of table component and not to table now, so we need that height value to include header and footer height

2023-10-13 11:38 UTC, sunnyparspec21 approved these changes

2023-10-19 10:39 UTC, merged