Md 8033 v1 : Create color picker component
Parspec/parspec-pixel pull request #223
Opened 2023-09-21 07:37 UTC by abhishekraj1007

2023-09-21 07:58 UTC, atul2103 requested changes

2023-09-21 07:58 UTC, atul2103 commented on src/components/ColorPicker/index.tsx
> +
move mui import above the box and popper imports

2023-09-21 07:58 UTC, atul2103 commented on src/components/Popper/index.tsx
> +export { Fade };
why Fade is exported.

2023-09-21 07:58 UTC, atul2103 commented on src/components/Popper/index.tsx
> +export const CustomPopper: React.FC<PopperProps> = ({ children, ...props }) => {
why this is not default export.

2023-09-21 07:58 UTC, atul2103 commented on src/components/ColorPicker/index.tsx
> +                                    <Box sx={{ m: 2 }}>
can we import fade directly here from MUI

2023-09-21 07:58 UTC, atul2103 commented on src/components/ColorPicker/index.tsx
> +                                    <Box sx={{ m: 2 }}>
we can pass m={2} directly without sx

2023-09-21 07:58 UTC, atul2103 commented on src/components/ColorPicker/index.tsx
> +export const TransitionsColorPicker: React.FC<ITransitionsColorPicker> = ({ color, onChange, onClickAway = () => {} }) => {
can we export it as default ?

2023-09-21 08:10 UTC, abhishekraj1007 commented on src/components/ColorPicker/index.tsx
> +
done

2023-09-21 08:11 UTC, abhishekraj1007 commented on src/components/Popper/index.tsx
> +export { Fade };
done

2023-09-21 08:14 UTC, abhishekraj1007 commented on src/components/Popper/index.tsx
> +export const CustomPopper: React.FC<PopperProps> = ({ children, ...props }) => {
done

2023-09-21 08:14 UTC, abhishekraj1007 commented on src/components/ColorPicker/index.tsx
> +                                    <Box sx={{ m: 2 }}>
we can

2023-09-21 08:15 UTC, abhishekraj1007 commented on src/components/ColorPicker/index.tsx
> +export const TransitionsColorPicker: React.FC<ITransitionsColorPicker> = ({ color, onChange, onClickAway = () => {} }) => {
let it be named export since there are two variations of colorPicker component

2023-09-21 08:43 UTC, atul2103 approved these changes

2023-09-21 10:23 UTC, sunnyparspec21 approved these changes

2023-10-13 10:11 UTC, abhijit-parspec commented on src/components/Popper/index.tsx
> +export default function CustomPopper({ children, ...props }: PopperProps) {
@abhishekraj1007 , keep the name as `Popper` only, no need to have the name as CustomPopper

2023-10-14 10:35 UTC, abhishekraj1007 commented on src/components/Popper/index.tsx
> +export default function CustomPopper({ children, ...props }: PopperProps) {
Done

2023-10-16 07:08 UTC, abhijit-parspec approved these changes

2023-10-16 07:08 UTC, merged