Md 9577: Create AGGrid Table Component in pixel
Parspec/parspec-pixel pull request #246
Opened 2023-12-19 06:23 UTC by hrishi-Parspec

JIRA: https://parspec.atlassian.net/browse/MD-9577

2024-01-09 07:31 UTC, Charul-Parspec requested changes

2024-01-09 07:31 UTC, Charul-Parspec commented on src/components/AgGridTable/Table.tsx
> +    noRowsOverlayComponent?: (props: any) => JSX.Element;
loadingOverlayComponent, noRowsOverlayComponent will be common for all tables, so it should be directly added in the component and not to be accepted as props @hrishi-Parspec

2024-01-09 07:31 UTC, Charul-Parspec commented on src/components/AgGridTable/Table.tsx
> +    toolbarRightSection?: React.ReactNode;
@hrishi-Parspec Same comments as CustomToolbarPanel props comment ^

2024-01-09 07:31 UTC, Charul-Parspec commented on src/components/AgGridTable/Table.tsx
> +        api: {
@hrishi-Parspec I would suggest you expose grid api here rather than some methods. Currently multiple methods of api are being used and even if we add those here, in future the methods might increase and it is safe to use grid api so no point in encapsulating/hiding grid api

2024-01-09 07:31 UTC, Charul-Parspec commented on src/components/AgGridTable/data.tsx
it can be just ts file since no jsx is used @hrishi-Parspec

2024-01-09 07:45 UTC, sunnyparspec21 requested changes

2024-01-09 07:45 UTC, sunnyparspec21 commented on src/components/AgGridTable/Table.tsx
> +    noRowsOverlayComponent?: (props: any) => JSX.Element;
+1

2024-01-09 07:45 UTC, sunnyparspec21 commented on src/components/AgGridTable/Table.tsx
> +    processCellForClipboard?: (props: ProcessCellForExportParams) => any;
why any?

2024-01-10 08:46 UTC, hrishi-Parspec commented on src/components/AgGridTable/CustomToolbarPanel.tsx
> +
done

2024-01-10 13:05 UTC, hrishi-Parspec commented on src/components/AgGridTable/CustomToolbarPanel.tsx
> +    disabledToolBarButton: boolean;
done

2024-01-10 13:05 UTC, hrishi-Parspec commented on src/components/AgGridTable/CustomToolbarPanel.tsx
> +    onTextSearch?: (searchString: string) => void;
changed prop name for CustomToolbarPanel.tsx
Let me know if i need to change it for AGGridTable.tsx file as well

2024-01-10 13:42 UTC, hrishi-Parspec commented on src/components/AgGridTable/CustomToolbarPanel.tsx
> +    closeBanner: () => void;
done

2024-01-10 13:49 UTC, hrishi-Parspec commented on src/components/AgGridTable/Table.tsx
> +    columnDefs: (ColDef | ColGroupDef)[] | null;
Yes, because same was mentioned in the docs:
https://www.ag-grid.com/react-data-grid/grid-options/#reference-columns-columnDefs

2024-01-10 13:50 UTC, hrishi-Parspec commented on src/components/AgGridTable/Table.tsx
> +    getRowStyle?: () => {} | undefined;
changed

2024-01-10 13:51 UTC, hrishi-Parspec commented on src/components/AgGridTable/Table.tsx
> +    pinnedBottomRowData?: any[];
changed it to `Array<Record<string, any>>`

2024-01-10 14:03 UTC, hrishi-Parspec commented on src/components/AgGridTable/Table.tsx
> +    noRowsOverlayComponent?: (props: any) => JSX.Element;
done

2024-01-10 14:30 UTC, hrishi-Parspec commented on src/components/AgGridTable/Table.tsx
> +    toolbarRightSection?: React.ReactNode;
changed `onTextSearch`  to `onSearchChange`

2024-01-10 17:00 UTC, hrishi-Parspec commented on src/components/AgGridTable/data.tsx
done

2024-01-11 01:46 UTC, hrishi-Parspec commented on src/components/AgGridTable/CustomToolbarPanel.tsx
> +
done

2024-01-11 01:51 UTC, hrishi-Parspec commented on src/components/AgGridTable/Table.tsx
> +    processCellForClipboard?: (props: ProcessCellForExportParams) => any;
`any` because it returns a function

reference: https://www.ag-grid.com/react-data-grid/range-selection/#example-advanced-range-selection

2024-01-29 10:00 UTC, Charul-Parspec commented on src/components/AgGridTable/Table.tsx
> +    tableData: Object[];
@hrishi-Parspec this should be Object[] | null

2024-04-17 09:12 UTC, hrishi-Parspec commented on src/components/AgGridTable/Table.tsx
> +        api: {
done

2024-04-17 09:32 UTC, hrishi-Parspec commented on src/components/AgGridTable/Table.tsx
> +    tableData: Object[];
tableData prop has been removed

2024-04-17 09:42 UTC, hrishi-Parspec commented on src/components/AgGridTable/Table.tsx
> +    isTableLoading: boolean;
changed isTableLoading to isLoading

2024-04-17 09:48 UTC, Charul-Parspec commented on src/components/AgGridTable/Table.tsx
> +                />
@hrishi-Parspec add reactiveComponet true prop. Refer: https://www.ag-grid.com/react-data-grid/components/#registering-custom-components

2024-04-24 09:58 UTC, Charul-Parspec commented on src/components/AgGridTable/CustomToolbarPanel.tsx
> +    onTextSearch?: (searchString: string) => void;
@hrishi-Parspec yes that was needed

2024-04-24 10:00 UTC, Charul-Parspec commented on src/components/AgGridTable/CustomToolbarPanel.tsx
> +
@hrishi-Parspec this is not done yet

2024-04-24 10:01 UTC, Charul-Parspec commented on src/components/AgGridTable/CustomToolbarPanel.tsx
> +    disabledToolBarButton: boolean;
@hrishi-Parspec can see the same props present. the change was not done

2024-04-24 10:02 UTC, Charul-Parspec commented on src/components/AgGridTable/CustomToolbarPanel.tsx
> +    closeBanner: () => void;
@hrishi-Parspec this is still pending

2024-04-24 10:03 UTC, Charul-Parspec commented on src/components/AgGridTable/Table.tsx
> +    toolbarRightSection?: React.ReactNode;
@hrishi-Parspec this is still pending

2024-04-24 10:04 UTC, Charul-Parspec commented on src/components/AgGridTable/Table.tsx
> +                />
@hrishi-Parspec this is still pending

2024-04-24 12:40 UTC, Charul-Parspec approved these changes

2024-04-24 12:49 UTC, sunnyparspec21 approved these changes

2024-04-24 12:50 UTC, merged