MD-9419 commit for right side in accordion
Parspec/parspec-pixel pull request #254
Opened 2024-01-08 05:34 UTC by gautamkr04

Desc - REQ - PF - Product Finder select product screen redesign

Jira - https://parspec.atlassian.net/browse/MD-9419

2024-01-08 07:09 UTC, atul2103 requested changes

2024-01-08 07:09 UTC, atul2103 commented on src/components/Accordion/index.tsx
> +                                <Box sx={commonSxStyles}>{item.rightSummary}</Box>
since rightSummary is not required, can we add a condition that if rightSummary exists then only render this Box.

2024-01-08 11:45 UTC, Charul-Parspec commented on src/components/Accordion/index.tsx
> +import { Box } from '../Box';
@gautamkr04 Add space in between mui imports and local imports

2024-01-08 12:17 UTC, sunnyparspec21 reviewed
Have same feedbacks that @atul2103 and @Charul-Parspec have shared, other things looks good to me

2024-01-08 12:17 UTC, sunnyparspec21 commented on src/components/Accordion/index.tsx
> +import { Box } from '../Box';
+1

2024-01-08 12:17 UTC, sunnyparspec21 commented on src/components/Accordion/index.tsx
> +                                <Box sx={commonSxStyles}>{item.rightSummary}</Box>
+1

2024-01-09 06:19 UTC, gautamkr04 commented on src/components/Accordion/index.tsx
> +                                <Box sx={commonSxStyles}>{item.rightSummary}</Box>
`{item?.rightSummary && <Box sx={commonSxStyles}>{item.rightSummary}</Box>}`
Added it ,Done.

2024-01-09 06:19 UTC, gautamkr04 commented on src/components/Accordion/index.tsx
> +import { Box } from '../Box';
Done

2024-02-07 07:00 UTC, abhijit-parspec approved these changes

2024-02-07 07:01 UTC, merged