MD-10135 Ability to Highlight specific line items on the final quote
Parspec/parspec-pixel pull request #268
Opened 2024-03-19 12:26 UTC by gautamkr04

desc : -Ability to Highlight specific line items on the final quote
https://parspec.atlassian.net/browse/MD-10135

2024-03-20 10:56 UTC, Charul-Parspec requested changes

2024-03-20 10:56 UTC, Charul-Parspec commented on src/components/Table/Table.tsx
> +type ToolbarT = 'delete' | 'search' | 'clearFilters' | 'hide' | 'unhide' | 'selectedItems' | 'duplicate' | 'add' | 'move' | 'createKit' | 'highLight';
```suggestion
type ToolbarT = 'delete' | 'search' | 'clearFilters' | 'hide' | 'unhide' | 'selectedItems' | 'duplicate' | 'add' | 'move' | 'createKit' | 'highlight';
```

2024-03-22 07:07 UTC, gautamkr04 commented on src/components/Table/Table.tsx
> +type ToolbarT = 'delete' | 'search' | 'clearFilters' | 'hide' | 'unhide' | 'selectedItems' | 'duplicate' | 'add' | 'move' | 'createKit' | 'highLight';
Done

2024-03-28 05:37 UTC, Charul-Parspec approved these changes

2024-03-28 05:37 UTC, merged