Md 10986 :  Added Forced Expand and Collapsed in the Accordion Component in the Pixel
Parspec/parspec-pixel pull request #269
Opened 2024-03-25 13:31 UTC by abhishekraj1007

jira : https://parspec.atlassian.net/browse/MD-10986

2024-04-08 09:18 UTC, Charul-Parspec requested changes

2024-04-08 09:18 UTC, Charul-Parspec commented on src/components/Accordion/index.tsx
> +    const [isAccExpanded, setIsAccExpanded] = useState<string | false>(options[0]['labelId']);
@abhishekraj1007 any reason for maintaining a prop and state for expanded. I think the accordion should not be controlled from state, it should be controlled from props

2024-04-08 09:55 UTC, abhishekraj1007 commented on src/components/Accordion/index.tsx
> +    const [isAccExpanded, setIsAccExpanded] = useState<string | false>(options[0]['labelId']);
we are making the component stateful because withing the Accordion there can be multiple  options and labels. The state maintained there makes sure we are expending /collapsing the selected label only. @Charul-Parspec

2024-04-16 09:13 UTC, Charul-Parspec approved these changes

2024-04-16 09:13 UTC, merged