Md 11642 v4 : Background color change for customer tabs and added border
Parspec/parspec-pixel pull request #279
Opened 2024-05-03 14:33 UTC by abhishekraj1007

jira : https://parspec.atlassian.net/browse/MD-11642

2024-05-06 12:24 UTC, Charul-Parspec requested changes

2024-05-06 12:24 UTC, Charul-Parspec commented on src/components/Tabs/index.tsx
> +            sx={orientation === 'horizontal' ? { borderBottom: 1, borderColor: 'divider' } : { borderRight: 1, borderColor: 'divider', height: 'inherit' }}
@abhishekraj1007 this can be handled inside CustomTabs styled css like isEnableTabsBackground

2024-05-06 12:25 UTC, Charul-Parspec commented on src/components/Tabs/index.tsx
> +                    sx={isEnableTabsBackground ? { alignItems: 'flex-start', border: 1, borderColor: 'neutral.main', color: 'inherit' } : { alignItems: 'flex-start' }}
since you are handling tabs with styled component, this sx can also be skipped. @abhishekraj1007

2024-05-06 12:28 UTC, abhishekraj1007 commented on src/components/Tabs/index.tsx
> +                    sx={isEnableTabsBackground ? { alignItems: 'flex-start', border: 1, borderColor: 'neutral.main', color: 'inherit' } : { alignItems: 'flex-start' }}
This is for Tab. I am not handling Tab using Styled component @Charul-Parspec .

2024-05-06 12:32 UTC, abhishekraj1007 commented on src/components/Tabs/index.tsx
> +            sx={orientation === 'horizontal' ? { borderBottom: 1, borderColor: 'divider' } : { borderRight: 1, borderColor: 'divider', height: 'inherit' }}
this will lead to multiple conditions like 
{ 
height : orientation === "vertical" ? 'inherit' : 'none',
border : orientation === "vertical" ? ....
}

2024-05-07 05:59 UTC, Charul-Parspec approved these changes

2024-05-07 06:02 UTC, merged