add: XS sizing to button and xs string to szie prop in MUI Button.d.t…
Parspec/parspec-pixel pull request #79
Opened 2023-04-06 08:25 UTC by hrishi-Parspec

Added "xs" sizing to button

2023-04-06 10:27 UTC, abhijit-parspec commented on src/components/Button/index.tsx
> +            sx={disabled || isLoading ? { opacity: 0.5, pointerEvents: 'none', ...(size === 'xs' ? XS_CLASS : {}) } : { ...(size === 'xs' ? XS_CLASS : {}) }}
```suggestion
            {SIZE==='XS && p:'0 1'}
```

2023-04-06 13:15 UTC, abhijit-parspec requested changes

2023-04-06 13:15 UTC, abhijit-parspec commented on src/components/Button/index.tsx
> +            sx={disabled || isLoading ? { opacity: 0.5, pointerEvents: 'none', ...(rest?.size === 'xs' && XS_STYLE) } : { ...(rest?.size === 'xs' && XS_STYLE) }}
```suggestion
            sx={{  
            ...(disabled || isLoading && {opacity: 0.5, pointerEvents: 'none'}),
              ...(size === 'xs' && XS_STYLE )
            }
```

2023-04-06 15:13 UTC, hrishi-Parspec commented on src/components/Button/index.tsx
> +            sx={disabled || isLoading ? { opacity: 0.5, pointerEvents: 'none', ...(rest?.size === 'xs' && XS_STYLE) } : { ...(rest?.size === 'xs' && XS_STYLE) }}
Hello Abhijit,
I have pulled out disabled from sx to make the code a bit more clean. 
Here's the new code

`disabled={disabled}`
` sx={{ ...(isLoading && { opacity: 0.5, pointerEvents: 'none' }), ...(rest?.size === 'xs' && XS_STYLE) }}`

2023-04-07 13:05 UTC, abhijit-parspec approved these changes

2023-04-07 13:05 UTC, merged